newrelic:
  build: .
  container_name: newrelic
  restart: always
  privileged: true
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/dev:/dev"
    - "/sys:/sys"
  env_file:
    - newrelic.env
  pid: host
  net: host
